
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IActualTrafficPerformance", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IActualTrafficPerformance {


    /**
     * 
     * @return
     *     returns cz.vutbr.fit.kordis.ActualTrafficPerformanceResp
     */
    @WebMethod(operationName = "GetActualTrafficPerformance", action = "http://tempuri.org/IActualTrafficPerformance/GetActualTrafficPerformance")
    @WebResult(name = "GetActualTrafficPerformanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetActualTrafficPerformance", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetActualTrafficPerformance")
    @ResponseWrapper(localName = "GetActualTrafficPerformanceResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetActualTrafficPerformanceResponse")
    public ActualTrafficPerformanceResp getActualTrafficPerformance();

}
