
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IElpInfo", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IElpInfo {


    /**
     * 
     * @return
     *     returns cz.vutbr.fit.kordis.ArrayOfElpInfoResp
     */
    @WebMethod(operationName = "GetPanelsInfo", action = "http://tempuri.org/IElpInfo/GetPanelsInfo")
    @WebResult(name = "GetPanelsInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPanelsInfo", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetPanelsInfo")
    @ResponseWrapper(localName = "GetPanelsInfoResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetPanelsInfoResponse")
    public ArrayOfElpInfoResp getPanelsInfo();

}
