
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILineRouteDelay", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILineRouteDelay {


    /**
     * 
     * @param routeID
     * @param lineID
     * @return
     *     returns cz.vutbr.fit.kordis.LineRouteDelayResp
     */
    @WebMethod(operationName = "GetLineRouteDelay", action = "http://tempuri.org/ILineRouteDelay/GetLineRouteDelay")
    @WebResult(name = "GetLineRouteDelayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLineRouteDelay", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetLineRouteDelay")
    @ResponseWrapper(localName = "GetLineRouteDelayResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetLineRouteDelayResponse")
    public LineRouteDelayResp getLineRouteDelay(
        @WebParam(name = "lineID", targetNamespace = "http://tempuri.org/")
        Long lineID,
        @WebParam(name = "routeID", targetNamespace = "http://tempuri.org/")
        Integer routeID);

}
