
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "INearDeparturesService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface INearDeparturesService {


    /**
     * 
     * @param stopID
     * @param postID
     * @return
     *     returns cz.vutbr.fit.kordis.NearDeparturesResp
     */
    @WebMethod(operationName = "GetNearDepartures", action = "http://tempuri.org/INearDeparturesService/GetNearDepartures")
    @WebResult(name = "GetNearDeparturesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNearDepartures", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDepartures")
    @ResponseWrapper(localName = "GetNearDeparturesResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesResponse")
    public NearDeparturesResp getNearDepartures(
        @WebParam(name = "stopID", targetNamespace = "http://tempuri.org/")
        Integer stopID,
        @WebParam(name = "postID", targetNamespace = "http://tempuri.org/")
        Short postID);

    /**
     * 
     * @param stopID
     * @param postID
     * @param departuresCount
     * @return
     *     returns cz.vutbr.fit.kordis.NearDeparturesResp
     */
    @WebMethod(operationName = "GetNearDeparturesWithCount", action = "http://tempuri.org/INearDeparturesService/GetNearDeparturesWithCount")
    @WebResult(name = "GetNearDeparturesWithCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNearDeparturesWithCount", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesWithCount")
    @ResponseWrapper(localName = "GetNearDeparturesWithCountResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesWithCountResponse")
    public NearDeparturesResp getNearDeparturesWithCount(
        @WebParam(name = "stopID", targetNamespace = "http://tempuri.org/")
        Integer stopID,
        @WebParam(name = "postID", targetNamespace = "http://tempuri.org/")
        Short postID,
        @WebParam(name = "departuresCount", targetNamespace = "http://tempuri.org/")
        Short departuresCount);

    /**
     * 
     * @param hour
     * @param stopID
     * @param postID
     * @param minute
     * @return
     *     returns cz.vutbr.fit.kordis.NearDeparturesResp
     */
    @WebMethod(operationName = "GetNearDeparturesByTime", action = "http://tempuri.org/INearDeparturesService/GetNearDeparturesByTime")
    @WebResult(name = "GetNearDeparturesByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNearDeparturesByTime", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesByTime")
    @ResponseWrapper(localName = "GetNearDeparturesByTimeResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesByTimeResponse")
    public NearDeparturesResp getNearDeparturesByTime(
        @WebParam(name = "stopID", targetNamespace = "http://tempuri.org/")
        Integer stopID,
        @WebParam(name = "postID", targetNamespace = "http://tempuri.org/")
        Short postID,
        @WebParam(name = "hour", targetNamespace = "http://tempuri.org/")
        Short hour,
        @WebParam(name = "minute", targetNamespace = "http://tempuri.org/")
        Short minute);

    /**
     * 
     * @param hour
     * @param stopID
     * @param postID
     * @param departuresCount
     * @param minute
     * @return
     *     returns cz.vutbr.fit.kordis.NearDeparturesResp
     */
    @WebMethod(operationName = "GetNearDeparturesByTimeWithCount", action = "http://tempuri.org/INearDeparturesService/GetNearDeparturesByTimeWithCount")
    @WebResult(name = "GetNearDeparturesByTimeWithCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNearDeparturesByTimeWithCount", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesByTimeWithCount")
    @ResponseWrapper(localName = "GetNearDeparturesByTimeWithCountResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesByTimeWithCountResponse")
    public NearDeparturesResp getNearDeparturesByTimeWithCount(
        @WebParam(name = "stopID", targetNamespace = "http://tempuri.org/")
        Integer stopID,
        @WebParam(name = "postID", targetNamespace = "http://tempuri.org/")
        Short postID,
        @WebParam(name = "hour", targetNamespace = "http://tempuri.org/")
        Short hour,
        @WebParam(name = "minute", targetNamespace = "http://tempuri.org/")
        Short minute,
        @WebParam(name = "departuresCount", targetNamespace = "http://tempuri.org/")
        Short departuresCount);

    /**
     * 
     * @param stopID
     * @return
     *     returns cz.vutbr.fit.kordis.NearDeparturesWithPostsResp
     */
    @WebMethod(operationName = "GetNearDeparturesAcrossPosts", action = "http://tempuri.org/INearDeparturesService/GetNearDeparturesAcrossPosts")
    @WebResult(name = "GetNearDeparturesAcrossPostsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNearDeparturesAcrossPosts", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesAcrossPosts")
    @ResponseWrapper(localName = "GetNearDeparturesAcrossPostsResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetNearDeparturesAcrossPostsResponse")
    public NearDeparturesWithPostsResp getNearDeparturesAcrossPosts(
        @WebParam(name = "stopID", targetNamespace = "http://tempuri.org/")
        Integer stopID);

}
