
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRouteOnCall", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRouteOnCall {


    /**
     * 
     * @param statinID
     * @param date
     * @param routeID
     * @param action
     * @param lineNum
     * @param ticketID
     * @return
     *     returns cz.vutbr.fit.kordis.RouteOnCallResp
     */
    @WebMethod(operationName = "ResolveIncRoCOrder", action = "http://tempuri.org/IRouteOnCall/ResolveIncRoCOrder")
    @WebResult(name = "ResolveIncRoCOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResolveIncRoCOrder", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.ResolveIncRoCOrder")
    @ResponseWrapper(localName = "ResolveIncRoCOrderResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.ResolveIncRoCOrderResponse")
    public RouteOnCallResp resolveIncRoCOrder(
        @WebParam(name = "action", targetNamespace = "http://tempuri.org/")
        WebRoCOrderMsgServerSinkEAction action,
        @WebParam(name = "ticketID", targetNamespace = "http://tempuri.org/")
        Long ticketID,
        @WebParam(name = "lineNum", targetNamespace = "http://tempuri.org/")
        Long lineNum,
        @WebParam(name = "routeID", targetNamespace = "http://tempuri.org/")
        Short routeID,
        @WebParam(name = "statinID", targetNamespace = "http://tempuri.org/")
        Integer statinID,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date);

    /**
     * 
     * @param ticketID
     * @return
     *     returns cz.vutbr.fit.kordis.RouteOnCallResp
     */
    @WebMethod(operationName = "ResolveIncRoCStorno", action = "http://tempuri.org/IRouteOnCall/ResolveIncRoCStorno")
    @WebResult(name = "ResolveIncRoCStornoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResolveIncRoCStorno", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.ResolveIncRoCStorno")
    @ResponseWrapper(localName = "ResolveIncRoCStornoResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.ResolveIncRoCStornoResponse")
    public RouteOnCallResp resolveIncRoCStorno(
        @WebParam(name = "ticketID", targetNamespace = "http://tempuri.org/")
        Long ticketID);

    /**
     * 
     * @param date
     * @param line
     * @param stationID
     * @return
     *     returns cz.vutbr.fit.kordis.ListForRouteOfCallResp
     */
    @WebMethod(operationName = "GetListForRouteOfCall", action = "http://tempuri.org/IRouteOnCall/GetListForRouteOfCall")
    @WebResult(name = "GetListForRouteOfCallResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetListForRouteOfCall", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetListForRouteOfCall")
    @ResponseWrapper(localName = "GetListForRouteOfCallResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetListForRouteOfCallResponse")
    public ListForRouteOfCallResp getListForRouteOfCall(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date,
        @WebParam(name = "stationID", targetNamespace = "http://tempuri.org/")
        Integer stationID,
        @WebParam(name = "line", targetNamespace = "http://tempuri.org/")
        Integer line);

}
