
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStopInfo", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IStopInfo {


    /**
     * 
     * @param id
     * @return
     *     returns cz.vutbr.fit.kordis.StopInfoResponse
     */
    @WebMethod(operationName = "GetStopInfo", action = "http://tempuri.org/IStopInfo/GetStopInfo")
    @WebResult(name = "GetStopInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStopInfo", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetStopInfo")
    @ResponseWrapper(localName = "GetStopInfoResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetStopInfoResponse")
    public StopInfoResponse getStopInfo(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

}
