
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITrafficState", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITrafficState {


    /**
     * 
     * @return
     *     returns cz.vutbr.fit.kordis.TrafficStateResp
     */
    @WebMethod(operationName = "GetTrafficState", action = "http://tempuri.org/ITrafficState/GetTrafficState")
    @WebResult(name = "GetTrafficStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTrafficState", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTrafficState")
    @ResponseWrapper(localName = "GetTrafficStateResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTrafficStateResponse")
    public TrafficStateResp getTrafficState();

    /**
     * 
     * @return
     *     returns cz.vutbr.fit.kordis.TrafficStateResp
     */
    @WebMethod(operationName = "GetTrafficStateVLDBusWoService", action = "http://tempuri.org/ITrafficState/GetTrafficStateVLDBusWoService")
    @WebResult(name = "GetTrafficStateVLDBusWoServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTrafficStateVLDBusWoService", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTrafficStateVLDBusWoService")
    @ResponseWrapper(localName = "GetTrafficStateVLDBusWoServiceResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTrafficStateVLDBusWoServiceResponse")
    public TrafficStateResp getTrafficStateVLDBusWoService();

    /**
     * 
     * @return
     *     returns cz.vutbr.fit.kordis.TrafficStateResp
     */
    @WebMethod(operationName = "GetTrafficStateDPMBWoService", action = "http://tempuri.org/ITrafficState/GetTrafficStateDPMBWoService")
    @WebResult(name = "GetTrafficStateDPMBWoServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTrafficStateDPMBWoService", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTrafficStateDPMBWoService")
    @ResponseWrapper(localName = "GetTrafficStateDPMBWoServiceResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTrafficStateDPMBWoServiceResponse")
    public TrafficStateResp getTrafficStateDPMBWoService();

}
