
package cz.vutbr.fit.live.kordis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITweetsOnLines", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITweetsOnLines {


    /**
     * 
     * @return
     *     returns cz.vutbr.fit.kordis.ArrayOfTweetsOnLinesResp
     */
    @WebMethod(operationName = "GetTweets", action = "http://tempuri.org/ITweetsOnLines/GetTweets")
    @WebResult(name = "GetTweetsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTweets", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTweets")
    @ResponseWrapper(localName = "GetTweetsResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTweetsResponse")
    public ArrayOfTweetsOnLinesResp getTweets();

    /**
     * 
     * @param linesL
     * @return
     *     returns cz.vutbr.fit.kordis.ArrayOfTweetsOnLinesResp
     */
    @WebMethod(operationName = "GetTweetsForLines", action = "http://tempuri.org/ITweetsOnLines/GetTweetsForLines")
    @WebResult(name = "GetTweetsForLinesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTweetsForLines", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTweetsForLines")
    @ResponseWrapper(localName = "GetTweetsForLinesResponse", targetNamespace = "http://tempuri.org/", className = "cz.vutbr.fit.kordis.GetTweetsForLinesResponse")
    public ArrayOfTweetsOnLinesResp getTweetsForLines(
        @WebParam(name = "linesL", targetNamespace = "http://tempuri.org/")
        ArrayOfint linesL);

}
